console.log('konnichiwa!')
console.log(5*5)
console.log('chicken or beef?')
alert('Has anyone told u today how awesome Shoko is?')
alert('Jk, YOU are awesome! Have a great day!')
console.log('took me the whole weekend to figure out how to change the directory.  great stay-home material for social-distancing holiday wknd! :P')
console.log("I'm a slow learner but never stop learning!")